language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - jruby-9.1.15.0
gemfile:
  - gemfiles/rails1-4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails5.gemfile
      rvm: 2.1.10
    - gemfile: gemfiles/rails5.gemfile
      rvm: jruby-9.1.6.0

before_install:
  - gem update --system # use the very latest Rubygems
  - gem install bundler # use the very latest Bundler
