language: ruby
rvm:
  - 2.1.10
  - 2.2.8
  - 2.3.5
  - jruby-9.1.15.0
gemfile:
  - gemfiles/rails1-4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails5.gemfile
      rvm: 1.9.3
    - gemfile: gemfiles/rails5.gemfile
      rvm: 2.0.0
    - gemfile: gemfiles/rails5.gemfile
      rvm: 2.1.9
    - gemfile: gemfiles/rails5.gemfile
      rvm: jruby-9.1.6.0
before_install:
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7
  - gem --version
