language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - jruby-9.1.6.0
gemfile:
  - gemfiles/rails1-4.gemfile
  - gemfiles/rails5.gemfile
matrix:
  exclude:
    - gemfile: gemfiles/rails5.gemfile
      rvm: 1.9.3
    - gemfile: gemfiles/rails5.gemfile
      rvm: 2.0.0
    - gemfile: gemfiles/rails5.gemfile
      rvm: 2.1.9
    - gemfile: gemfiles/rails5.gemfile
      rvm: jruby-9.1.6.0

before_install:
  - gem update --system # use the very latest Rubygems
  - gem install bundler # use the very latest Bundler
